CREATE TABLE IF NOT EXISTS users (
    username    VARCHAR(50)  NOT NULL,
    password    VARCHAR(100) NOT NULL,
    full_name   VARCHAR(100),
    email       VARCHAR(100),
    phone       VARCHAR(20),
    PRIMARY KEY (username)
);

CREATE TABLE IF NOT EXISTS user_roles (
    user_role_id INTEGER GENERATED ALWAYS AS IDENTITY,
    username     VARCHAR(50) NOT NULL,
    role         VARCHAR(50) NOT NULL,
    PRIMARY KEY (user_role_id),
    FOREIGN KEY (username) REFERENCES users(username)
);

CREATE TABLE IF NOT EXISTS lecture (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    title   VARCHAR(255),
    summary VARCHAR(2000),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS attachment (
    id           UUID DEFAULT random_uuid() NOT NULL,
    content      BLOB,
    content_type VARCHAR(255),
    filename     VARCHAR(255),
    lecture_id   BIGINT,
    PRIMARY KEY (id),
    FOREIGN KEY (lecture_id) REFERENCES lecture(id)
);

CREATE TABLE IF NOT EXISTS poll (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    question VARCHAR(500),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS poll_option (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    option_text VARCHAR(255),
    vote_count  INTEGER DEFAULT 0,
    poll_id     BIGINT,
    PRIMARY KEY (id),
    FOREIGN KEY (poll_id) REFERENCES poll(id)
);

CREATE TABLE IF NOT EXISTS vote (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    username       VARCHAR(50),
    poll_id        BIGINT,
    poll_option_id BIGINT,
    PRIMARY KEY (id),
    FOREIGN KEY (poll_id) REFERENCES poll(id),
    FOREIGN KEY (poll_option_id) REFERENCES poll_option(id)
);

CREATE TABLE IF NOT EXISTS comment (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    username   VARCHAR(50),
    content    VARCHAR(2000),
    created_at TIMESTAMP,
    lecture_id BIGINT,
    poll_id    BIGINT,
    PRIMARY KEY (id),
    FOREIGN KEY (lecture_id) REFERENCES lecture(id),
    FOREIGN KEY (poll_id) REFERENCES poll(id)
);
